-- WARMONGERPOINTS PER ERA

-- DEFAULT = 0
UPDATE Eras SET WarmongerPoints=0 WHERE EraType='ERA_ANCIENT'; 
-- DEFAULT = 4
UPDATE Eras SET WarmongerPoints=2 WHERE EraType='ERA_CLASSICAL'; 
-- DEFAULT = 8
UPDATE Eras SET WarmongerPoints=4 WHERE EraType='ERA_MEDIEVAL'; 
-- DEFAULT = 12
UPDATE Eras SET WarmongerPoints=4 WHERE EraType='ERA_RENAISSANCE'; 
-- DEFAULT = 18
UPDATE Eras SET WarmongerPoints=2 WHERE EraType='ERA_INDUSTRIAL'; 
-- DEFAULT = 24
UPDATE Eras SET WarmongerPoints=2 WHERE EraType='ERA_MODERN'; 
-- DEFAULT = 24
UPDATE Eras SET WarmongerPoints=2 WHERE EraType='ERA_ATOMIC'; 
-- DEFAULT = 24
UPDATE Eras SET WarmongerPoints=4 WHERE EraType='ERA_INFORMATION'; 
	
-- TYPES OF WAR	
-- DEFAULT = 100	
UPDATE DiplomaticActions SET WarmongerPercent=20 WHERE DiplomaticActionType='DIPLOACTION_DECLARE_FORMAL_WAR';
-- DEFAULT = 100
UPDATE DiplomaticActions SET WarmongerPercent=50 WHERE DiplomaticActionType='DIPLOACTION_JOINT_WAR';
-- DEFAULT = 150
UPDATE DiplomaticActions SET WarmongerPercent=100 WHERE DiplomaticActionType='DIPLOACTION_DECLARE_SURPRISE_WAR';
-- DEFAULT = 50
UPDATE DiplomaticActions SET WarmongerPercent=10 WHERE DiplomaticActionType='DIPLOACTION_DECLARE_HOLY_WAR';
-- DEFAULT = 0
UPDATE DiplomaticActions SET WarmongerPercent=0 WHERE DiplomaticActionType='DIPLOACTION_DECLARE_LIBERATION_WAR';
-- DEFAULT = 0
UPDATE DiplomaticActions SET WarmongerPercent=0 WHERE DiplomaticActionType='DIPLOACTION_DECLARE_RECONQUEST_WAR';
-- DEFAULT = 0
UPDATE DiplomaticActions SET WarmongerPercent=0 WHERE DiplomaticActionType='DIPLOACTION_DECLARE_PROTECTORATE_WAR';
-- DEFAULT = 50
UPDATE DiplomaticActions SET WarmongerPercent=30 WHERE DiplomaticActionType='DIPLOACTION_DECLARE_COLONIAL_WAR';
-- DEFAULT = 75
UPDATE DiplomaticActions SET WarmongerPercent=50 WHERE DiplomaticActionType='DIPLOACTION_DECLARE_TERRITORIAL_WAR';

-- DEFAULT = 50
UPDATE GlobalParameters SET Value=50 WHERE Name='WARMONGER_CITY_PERCENT_OF_DOW';
-- DEFAULT = 200
UPDATE GlobalParameters SET Value=200 WHERE Name='WARMONGER_FINAL_MAJOR_CITY_MULTIPLIER';
-- DEFAULT = 100
UPDATE GlobalParameters SET Value=100 WHERE Name='WARMONGER_FINAL_MINOR_CITY_MULTIPLIER';
-- DEFAULT = 50
UPDATE GlobalParameters SET Value=50 WHERE Name='DIPLOMACY_WARMONGER_POINT_PERCENT_DECAY';
-- DEFAULT = 32
UPDATE GlobalParameters SET Value=32 WHERE Name='WARMONGER_LIBERATE_POINTS';
-- DEFAULT = 200
UPDATE GlobalParameters SET Value=100 WHERE Name='WARMONGER_RAZE_PENALTY_PERCENT';
-- DEFAULT = 100
UPDATE GlobalParameters SET Value=-100 WHERE Name='WARMONGER_STOP_OCCUPYING_REFUND_PERCENT';


--START OF WAR WEARINESS MOD
-- DEFAULT = 1
UPDATE GlobalParameters SET Value=0 WHERE Name='WAR_WEARINESS_LOSS_OVER_REQ_AMENITIES_NONFOUNDED_CITY';
-- DEFAULT = 1
UPDATE GlobalParameters SET Value=0 WHERE Name='WAR_WEARINESS_PER_COMBAT_IN_ALLIED_LANDS';
-- DEFAULT = 2
UPDATE GlobalParameters SET Value=1 WHERE Name='WAR_WEARINESS_PER_COMBAT_IN_FOREIGN_LANDS';
-- DEFAULT = 3
UPDATE GlobalParameters SET Value=1 WHERE Name='WAR_WEARINESS_PER_UNIT_KILLED';
-- DEFAULT = 10
UPDATE GlobalParameters SET Value=1 WHERE Name='WAR_WEARINESS_PER_WMD_LAUNCHED';
-- DEFAULT = 2
UPDATE GlobalParameters SET Value=0 WHERE Name='WAR_WEARINESS_LOSS_OVER_REQ_AMENITIES_AT_WAR_CITY';
-- DEFAULT = 16
UPDATE GlobalParameters SET Value=8 WHERE Name='WAR_WEARINESS_WARMONGER_BASE';
-- DEFAULT = 2000
UPDATE GlobalParameters SET Value=5000 WHERE Name='WAR_WEARINESS_DECAY_PEACE_DECLARED';
-- DEFAULT = 200
UPDATE GlobalParameters SET Value=500 WHERE Name='WAR_WEARINESS_DECAY_TURN_AT_PEACE';


-- RAZED PENALTIES

-- DEFAULT = -20
UPDATE ModifierArguments SET Value=-5 WHERE ModifierId='STANDARD_DIPLOMATIC_RAZED_MY_CITY' AND Name='InitialValue';
-- Default Value = 20
UPDATE ModifierArguments SET Value=5 WHERE ModifierId='STANDARD_DIPLOMATIC_RAZED_MY_CITY' AND Name='ReductionTurns';
UPDATE ModifierArguments SET Value=-1 WHERE ModifierId='STANDARD_DIPLOMATIC_RAZED_MY_CITY' AND Name='ReductionValue';

UPDATE ModifierArguments SET Value=1 WHERE ModifierId='STANDARD_DIPLOMATIC_WARMONGER' AND Name='ReductionTurns';
-- Penalty for occupying AI's City default value = -18
UPDATE ModifierArguments SET Value=0 WHERE ModifierId='STANDARD_DIPLOMATIC_OCCUPIED_CITY' AND Name='InitialValue';
UPDATE ModifierArguments SET Value=0 WHERE  ModifierId='STANDARD_DIPLOMATIC_OCCUPIED_FRIENDLY_CITY' AND Name='InitialValue';
