-- LEADER TRAITS
DELETE FROM LeaderTraits WHERE LeaderType='LEADER_JOHN_CURTIN';
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES
 ('LEADER_JOHN_CURTIN','TRAIT_LEADER_DIVINE_WIND'),
 ('LEADER_JOHN_CURTIN','TRAIT_LEADER_UNIT_ENGLISH_REDCOAT'),
 ('LEADER_JOHN_CURTIN','TRAIT_LEADER_UNIT_AMERICAN_ROUGH_RIDER'),
 ('LEADER_JOHN_CURTIN','TRAJANS_COLUMN_TRAIT'),
--  ('LEADER_JOHN_CURTIN','TRAIT_LEADER_PAX_BRITANNICA'),
--  ('LEADER_JOHN_CURTIN','TRAIT_LEADER_KILLER_OF_CYRUS'),
--  ('LEADER_JOHN_CURTIN','FLYING_SQUADRON_TRAIT'),
--  ('LEADER_JOHN_CURTIN','TRAIT_LEADER_ADVENTURES_ENKIDU'),
--  ('LEADER_JOHN_CURTIN','CULTURE_KILLS_TRAIT'),
--  ('LEADER_JOHN_CURTIN','TRAIT_LEADER_MELEE_COASTAL_RAIDS'),
--  ('LEADER_JOHN_CURTIN','TRAIT_LEADER_EL_ESCORIAL'),
--  ('LEADER_JOHN_CURTIN','TRAIT_LEADER_MEDITERRANEAN'),
--  ('LEADER_JOHN_CURTIN','TRAIT_LEADER_ROOSEVELT_COROLLARY'),
--  ('LEADER_JOHN_CURTIN','TRAIT_LEADER_HOLY_ROMAN_EMPEROR'),
--FROM DLC
--  ('LEADER_JOHN_CURTIN','TRAIT_LEADER_GIFTS_FOR_TLATOANI'),
--  ('LEADER_JOHN_CURTIN','TRAIT_LEADER_LITHUANIAN_UNION'),
--  ('LEADER_JOHN_CURTIN','TRAIT_LEADER_MAGNANIMOUS'),
--  ('LEADER_JOHN_CURTIN','TRAIT_LEADER_GRAND_EMBASSY'),
--  ('LEADER_JOHN_CURTIN','TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH'),
 ('LEADER_JOHN_CURTIN','TRAIT_LEADER_CITADEL_CIVILIZATION');
 
DELETE FROM CivilizationTraits WHERE CivilizationType='CIVILIZATION_AUSTRALIA';
 INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES 
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_TREASURE_FLEET'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_AMAZON'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_GOLDEN_LIBERTY'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_UNIT_AMERICAN_P51'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_UNIT_FRENCH_GARDE_IMPERIALE'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_UNIT_GREEK_HOPLITE'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_UNIT_GERMAN_UBOAT'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_UNIT_AZTEC_EAGLE_WARRIOR'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_UNIT_SUMERIAN_WAR_CART'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_UNIT_ENGLISH_SEADOG'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_UNIT_SPANISH_CONQUISTADOR'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_UNIT_POLISH_HUSSAR'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_ROYAL_NAVY_DOCKYARD'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_STREET_CARNIVAL'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_DISTRICT_ACROPOLIS'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_DISTRICT_HANSA'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_DISTRICT_BATH'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_DISTRICT_LAVRA'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_BUILDING_FILM_STUDIO'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_BUILDING_MADRASA'),
 --POLAND DLC
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_BUILDING_SUKIENNICE'),
 --AUSTRALIA DLC
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_IMPROVEMENT_OUTBACK_STATION'),
 ('CIVILIZATION_AUSTRALIA','TRAIT_CIVILIZATION_UNIT_DIGGER');
