-- CIVILIZATION TRAITS MADE BY GDG
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES 
																					  -- Suzerain
																					  ('LEADER_BARBAROSSA','TRAIT_GDG_CIVILIZATION_MELEE_EXTRA_UNITS_AI'),						
																					  ('LEADER_CATHERINE_DE_MEDICI','TRAIT_GDG_CIVILIZATION_MELEE_EXTRA_UNITS_AI'),						
																					  ('LEADER_CLEOPATRA','TRAIT_EXTRA_UNITS_HEAVY_CAVALRY_AI'),						
																					  ('LEADER_GANDHI','TRAIT_EXTRA_UNITS_HEAVY_CAVALRY_AI'),	
																					  ('LEADER_GILGAMESH','TRAIT_EXTRA_UNITS_HEAVY_CAVALRY_AI'),						
																					  ('LEADER_GORGO','TRAIT_GDG_CIVILIZATION_MELEE_EXTRA_UNITS_AI'),			  
																					  ('LEADER_HARDRADA','TRAIT_EXTRA_UNITS_NAVAL_RANGED_AI'),						
																					  ('LEADER_MVEMBA','TRAIT_GDG_CIVILIZATION_MELEE_EXTRA_UNITS_AI'),						
																					  ('LEADER_PEDRO','TRAIT_EXTRA_UNITS_NAVAL_RANGED_AI'),						
																					  ('LEADER_PERICLES','TRAIT_GDG_CIVILIZATION_MELEE_EXTRA_UNITS_AI'),								
																					  ('LEADER_SALADIN','TRAIT_EXTRA_UNITS_HEAVY_CAVALRY_AI'),						
																					  ('LEADER_TOMYRIS','TRAIT_EXTRA_UNITS_MELEE_AI'),						
																					  ('LEADER_TRAJAN','TRAIT_EXTRA_UNITS_MELEE_AI'),						
																					  ('LEADER_PHILIP_II','TRAIT_ALL_SUZERAIN_BONUSES'),						
																					  ('LEADER_MONTEZUMA','TRAIT_EXTRA_UNITS_MELEE_AI'),		
																					 -- 2 class type extra units leader
																					 -- ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_MELEE_EXTRA_UNITS_AI'),	
																					 -- ('LEADER_HOJO','TRAIT_EXTRA_UNITS_NAVAL_RANGED_AI'),
																					  ('LEADER_PETER_GREAT','TRAIT_EXTRA_UNITS_LIGHT_CAVALRY_AI'),
																					  ('LEADER_PETER_GREAT','TRAIT_EXTRA_UNITS_HEAVY_CAVALRY_AI'),				  
																					  ('LEADER_T_ROOSEVELT','TRAIT_EXTRA_UNITS_AIRCRAFT_UNITS_AI'),	
																					  ('LEADER_T_ROOSEVELT','TRAIT_EXTRA_UNITS_HEAVY_CAVALRY_AI'),			  
																					  ('LEADER_QIN','TRAIT_GDG_CIVILIZATION_MELEE_EXTRA_UNITS_AI'),	
																					  ('LEADER_QIN','TRAIT_EXTRA_UNITS_NAVAL_RANGED_AI'),	
																					  ('LEADER_VICTORIA','TRAIT_EXTRA_UNITS_NAVAL_RANGED_AI'),
																					  ('LEADER_VICTORIA','TRAIT_EXTRA_UNITS_MELEE_AI');

-- REFERENCES
-- LEADERS THAT CAN REPLACE LEADER_T_ROOSEVELT
-- LEADER_BARBAROSSA
-- LEADER_CATHERINE_DE_MEDICI
-- LEADER_CLEOPATRA
-- LEADER_GANDHI
-- LEADER_GILGAMESH
-- LEADER_GORGO
-- LEADER_HARDRADA
-- LEADER_HOJO
-- LEADER_MVEMBA
-- LEADER_PEDRO
-- LEADER_PERICLES
-- LEADER_PETER_GREAT
-- LEADER_PHILIP_II
-- LEADER_QIN
-- LEADER_SALADIN
-- LEADER_TOMYRIS
-- LEADER_TRAJAN
-- LEADER_T_ROOSEVELT
-- LEADER_VICTORIA
-- LEADER_MONTEZUMA