
-- Types
INSERT INTO Types (Type,Kind) VALUES ('TRAIT_GDG_CIVILIZATION_ADDITIONAL_UNIT_SETTLING_CITY','KIND_TRAIT');	

--Modifiers
INSERT INTO Modifiers (ModifierId,ModifierType,Permanent,SubjectRequirementSetId) VALUES ('TRAIT_CIVILIZATION_GDG_ADDITIONAL_UNIT_SETTLING_CITY_BUILDER','MODIFIER_PLAYER_CITIES_GRANT_UNIT_BY_CLASS',1,'CITY_NOT_OWNER_CAPITAL_CONTINENT_REQUIREMENTS');
--1 true 
--0 false

--Modifier Arguments
INSERT INTO ModifierArguments (ModifierId,Name,Value) VALUES ('TRAIT_CIVILIZATION_GDG_ADDITIONAL_UNIT_SETTLING_CITY_BUILDER','UnitType','UNIT_BUILDER');

--Traits
INSERT INTO Traits (TraitType,Name,Description) VALUES ('TRAIT_GDG_CIVILIZATION_ADDITIONAL_UNIT_SETTLING_CITY','LOC_TRAIT_CIVILIZATION_EXTRA_LIGHT_CAVALRY_NAME','LOC_TRAIT_CIVILIZATION_EXTRA_LIGHT_CAVALRY_DESCRIPTION');

--TraitModifiers
INSERT INTO TraitModifiers (TraitType,ModifierId) VALUES ('TRAIT_GDG_CIVILIZATION_ADDITIONAL_UNIT_SETTLING_CITY','TRAIT_CIVILIZATION_GDG_ADDITIONAL_UNIT_SETTLING_CITY_BUILDER');
