-- CIVILIZATION TRAITS MADE BY GDG
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES 
																					  -- Suzerain
																					  ('LEADER_HOJO','TRAIT_ALL_SUZERAIN_BONUSES'),						
																					  --Extra Units
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_EXTRA_UNITS'),
																					  --Border Growth
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_FASTER_BORDER_GROWTH'),
																					  --Builder Charge
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_MANY_BUILDER_CHARGE'),
																					  -- Settler Production
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_FASTEST_SETTLER_PROD'),
																					  --NEW EXTRA WILD CARD
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_EXTRA_WILD_CARD'),
																					  --NEW WONDER PRODUCTION	
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_WONDER_PRODUCTION'),
																					  --NEW District PRODUCTION	
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_DISTRICT_PRODUCTION'),
																					  --NEW Building Production
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_BUILDING_PRODUCTION'),
																					  -- Discount Unit Upgrade
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_UNIT_UPGRADE_DISCOUNT'),
																					  --City Growth Rate
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_CITY_GROWTH'),
																					  --City Tiles
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_CITY_TILES'),
																					  --City Production
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_PRODUCTION'),
																					  --TRADE
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_TRADE_YIELDS'),
																					  --PURCHASE USING FAITH
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_PURCHASE_UNITS_FAITH'),
																					  --Minor Open Borders , Influence Points , Religion Spread Distance, Religion Spread Strength
																					  ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_MO_IP_RSD_RSS');


-- UNIT PRODUCTION
-- LAND
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_MELEE_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_RANGED_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_ANTI_CAVALRY_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_SIEGE_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_SUPPORT_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_HEAVY_CAVALRY_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_LIGHT_CAVALRY_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_NAVAL_MELEE_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_NAVAL_RANGED_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_AIR_FIGHTER_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_AIR_BOMBER_PROD');



-- REFERENCES
-- LEADERS THAT CAN REPLACE LEADER_T_ROOSEVELT
-- LEADER_BARBAROSSA
-- LEADER_CATHERINE_DE_MEDICI
-- LEADER_CLEOPATRA
-- LEADER_GANDHI
-- LEADER_GILGAMESH
-- LEADER_GORGO
-- LEADER_HARDRADA
-- LEADER_HOJO
-- LEADER_MVEMBA
-- LEADER_PEDRO
-- LEADER_PERICLES
-- LEADER_PETER_GREAT
-- LEADER_T_ROOSEVELT
-- LEADER_QIN
-- LEADER_SALADIN
-- LEADER_TOMYRIS
-- LEADER_TRAJAN
-- LEADER_T_ROOSEVELT
-- LEADER_VICTORIA
-- LEADER_MONTEZUMA