--If you want to delete a triat just comment it like this
-- Suzerain
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_ALL_SUZERAIN_BONUSES');

-- CIVILIZATION TRAITS
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_EXTRA_UNITS');	
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_FASTER_BORDER_GROWTH');	
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_MANY_BUILDER_CHARGE');	
-- Settler Production
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_FASTEST_SETTLER_PROD');		
--NEW EXTRA WILD CARD
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_EXTRA_WILD_CARD');		
--NEW WONDER PRODUCTION	
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_WONDER_PRODUCTION');	
--NEW District PRODUCTION	
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_DISTRICT_PRODUCTION');
--NEW Building Production
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_BUILDING_PRODUCTION');
-- Discount Unit Upgrade
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_UNIT_UPGRADE_DISCOUNT');
--City Growth Rate
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_CITY_GROWTH');
--City Tiles
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_CITY_TILES');
--City Production
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_PRODUCTION');
--TRADE
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_TRADE_YIELDS');
--PURCHASE USING FAITH
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_PURCHASE_UNITS_FAITH');

-- UNIT PRODUCTION
-- LAND
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_MELEE_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_RANGED_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_ANTI_CAVALRY_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_SIEGE_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_SUPPORT_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_HEAVY_CAVALRY_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_LIGHT_CAVALRY_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_NAVAL_MELEE_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_NAVAL_RANGED_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_AIR_FIGHTER_PROD');
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES ('LEADER_HOJO','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_AIR_BOMBER_PROD');


-- REFERENCES
-- LEADERS THAT CAN REPLACE LEADER_HOJO
-- LEADER_BARBAROSSA
-- LEADER_CATHERINE_DE_MEDICI
-- LEADER_CLEOPATRA
-- LEADER_GANDHI
-- LEADER_GILGAMESH
-- LEADER_GORGO
-- LEADER_HARDRADA
-- LEADER_HOJO
-- LEADER_MVEMBA
-- LEADER_PEDRO
-- LEADER_PERICLES
-- LEADER_PETER_GREAT
-- LEADER_PHILIP_II
-- LEADER_QIN
-- LEADER_SALADIN
-- LEADER_TOMYRIS
-- LEADER_TRAJAN
-- LEADER_T_ROOSEVELT
-- LEADER_VICTORIA
-- LEADER_MONTEZUMA