-- LEADER TRAITS
ALTER TABLE CivilizationTraits ADD LeaderType TEXT;
ALTER TABLE LeaderTraits ADD CivilizationType TEXT;
-- UPDATE LeaderTraits SET CivilizationType='CIVILIZATION_JAPAN' WHERE LeaderType='LEADER_HOJO';
UPDATE CivilizationTraits SET LeaderType='LEADER_HOJO' WHERE CivilizationType=(SELECT CivilizationType FROM LeaderTraits WHERE LeaderType='LEADER_HOJO');
DELETE FROM LeaderTraits WHERE LeaderType='LEADER_HOJO';
-- DELETE FROM CivilizationTraits WHERE CivilizationType='CIVILIZATION_JAPAN' AND LeaderType='LEADER_HOJO';

INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES
 ('LEADER_HOJO','TRAIT_LEADER_DIVINE_WIND'),
 ('LEADER_HOJO','TRAIT_LEADER_UNIT_ENGLISH_REDCOAT'),
 ('LEADER_HOJO','TRAIT_LEADER_UNIT_AMERICAN_ROUGH_RIDER'),
 ('LEADER_HOJO','TRAJANS_COLUMN_TRAIT'),
 ('LEADER_HOJO','TRAIT_LEADER_PAX_BRITANNICA'),
 ('LEADER_HOJO','TRAIT_LEADER_KILLER_OF_CYRUS'),
 ('LEADER_HOJO','FLYING_SQUADRON_TRAIT'),
 -- ('LEADER_HOJO','TRAIT_LEADER_ADVENTURES_ENKIDU'),
 ('LEADER_HOJO','CULTURE_KILLS_TRAIT'),
 ('LEADER_HOJO','TRAIT_LEADER_MELEE_COASTAL_RAIDS'),
 ('LEADER_HOJO','TRAIT_LEADER_EL_ESCORIAL'),
 -- ('LEADER_HOJO','TRAIT_LEADER_MEDITERRANEAN'),
 ('LEADER_HOJO','TRAIT_LEADER_ROOSEVELT_COROLLARY'),
 ('LEADER_HOJO','TRAIT_LEADER_HOLY_ROMAN_EMPEROR'),
 -- ('LEADER_HOJO','TRAIT_LEADER_MAGNANIMOUS'),
 -- ('LEADER_HOJO','TRAIT_LEADER_GRAND_EMBASSY'),
 -- ('LEADER_HOJO','TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH'),
--FROM DLC
 ('LEADER_HOJO','TRAIT_LEADER_GIFTS_FOR_TLATOANI'),
 ('LEADER_HOJO','TRAIT_LEADER_LITHUANIAN_UNION'),
 ('LEADER_HOJO','TRAIT_LEADER_CITADEL_CIVILIZATION');
 
 
 -- CIVILIZATION TRAITS

-- ABILITIES
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES 
-- ('LEADER_HOJO','TRAIT_CIVILIZATION_ADJACENT_DISTRICTS'),
('LEADER_HOJO','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME'),
-- ('LEADER_HOJO','TRAIT_CIVILIZATION_MOTHER_RUSSIA'),
('LEADER_HOJO','TRAIT_CIVILIZATION_LAST_PROPHET'),
('LEADER_HOJO','TRAIT_CIVILIZATION_IMPERIAL_FREE_CITIES'),
('LEADER_HOJO','TRAIT_CIVILIZATION_TREASURE_FLEET'),
('LEADER_HOJO','TRAIT_CIVILIZATION_PLATOS_REPUBLIC'),
-- ('LEADER_HOJO','TRAIT_CIVILIZATION_ITERU'),
('LEADER_HOJO','TRAIT_CIVILIZATION_WONDER_TOURISM'),
('LEADER_HOJO','TRAIT_CIVILIZATION_NKISI'),
('LEADER_HOJO','TRAIT_CIVILIZATION_FIRST_CIVILIZATION');
-- ('LEADER_HOJO','TRAIT_CIVILIZATION_AMAZON');


-- UNITS

INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES 
('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_JAPANESE_SAMURAI'),
('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_AMERICAN_P51'),
('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_FRENCH_GARDE_IMPERIALE'),
('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_GREEK_HOPLITE'),
('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_GERMAN_UBOAT'),
('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_SUMERIAN_WAR_CART'),
('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_ENGLISH_SEADOG'),
('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_SPANISH_CONQUISTADOR'),
('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_RUSSIAN_COSSACK'),
-- ('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_BRAZILIAN_MINAS_GERAES'),
('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_ROMAN_LEGION');
-- ('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_ARABIAN_MAMLUK');

--Moar Mods Compatibility (just uncomment what civ you're using)
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES 
		-- ('CIVILIZATION_ARABIA' ,'TRAIT_CIVILIZATION_UNIT_CAMEL_ARCHER'),
		-- ('CIVILIZATION_ARABIA' ,'TRAIT_CIVILIZATION_UNIT_GHAZI'),
		-- ('CIVILIZATION_GREECE' ,'TRAIT_CIVILIZATION_UNIT_COMPANION_CAVALRY'),
		-- ('CIVILIZATION_GREECE' ,'TRAIT_CIVILIZATION_UNIT_ARMATOLOS'),
		-- ('CIVILIZATION_AMERICA' ,'TRAIT_CIVILIZATION_UNIT_MINUTEMAN'),
		-- ('CIVILIZATION_GERMANY' ,'TRAIT_CIVILIZATION_UNIT_LANDSKNECHT'),
		('LEADER_HOJO' ,'TRAIT_CIVILIZATION_UNIT_PANZER'),
		-- ('CIVILIZATION_SUMERIA' ,'TRAIT_CIVILIZATION_UNIT_PHALANX'),
		-- ('CIVILIZATION_SUMERIA' ,'TRAIT_CIVILIZATION_UNIT_VULTURE'),
		-- ('CIVILIZATION_CHINA' ,'TRAIT_CIVILIZATION_UNIT_CHOKONU'),
		-- ('CIVILIZATION_CHINA' ,'TRAIT_CIVILIZATION_UNIT_SHIGONG'),
		-- ('CIVILIZATION_ENGLAND' ,'TRAIT_CIVILIZATION_UNIT_LONGBOWMAN'),
		-- ('CIVILIZATION_INDIA' ,'TRAIT_CIVILIZATION_UNIT_MUGHAL_SOWAR'),
		-- ('CIVILIZATION_INDIA' ,'TRAIT_CIVILIZATION_UNIT_SEPOY'),
		-- ('CIVILIZATION_NORWAY' ,'TRAIT_CIVILIZATION_UNIT_HIRDMAN'),
		-- ('CIVILIZATION_RUSSIA' ,'TRAIT_CIVILIZATION_UNIT_DRUZHINA'),
		-- ('CIVILIZATION_RUSSIA' ,'TRAIT_CIVILIZATION_UNIT_T34'),
		-- ('CIVILIZATION_ROME' ,'TRAIT_CIVILIZATION_UNIT_EQUITE'),
		-- ('CIVILIZATION_ROME' ,'TRAIT_CIVILIZATION_UNIT_ONAGER'),
		-- ('CIVILIZATION_SPAIN' ,'TRAIT_CIVILIZATION_UNIT_JINETE'),
		-- ('CIVILIZATION_SPAIN' ,'TRAIT_CIVILIZATION_UNIT_TERCIO'),
		('LEADER_HOJO' ,'TRAIT_CIVILIZATION_UNIT_SOHEI'),
		('LEADER_HOJO' ,'TRAIT_CIVILIZATION_UNIT_YAMATO');
		-- ('CIVILIZATION_SCYTHIA' ,'TRAIT_CIVILIZATION_UNIT_AMAZON'),
		-- ('CIVILIZATION_SCYTHIA' ,'TRAIT_CIVILIZATION_UNIT_AMAZON_SCOUT'),
		-- ('CIVILIZATION_BRAZIL' ,'TRAIT_CIVILIZATION_UNIT_FATHERLAND_VOLUNTEER'),
		-- ('CIVILIZATION_BRAZIL' ,'TRAIT_CIVILIZATION_UNIT_BANDEIRANTE'),
		-- ('CIVILIZATION_EGYPT' ,'TRAIT_CIVILIZATION_UNIT_HYKSOS_BOWMAN'),
		-- ('CIVILIZATION_EGYPT' ,'TRAIT_CIVILIZATION_UNIT_WAR_GALLEY'),
		-- ('CIVILIZATION_FRANCE' ,'TRAIT_CIVILIZATION_UNIT_GENDARME'),
		-- ('CIVILIZATION_FRANCE' ,'TRAIT_CIVILIZATION_UNIT_FRENCH_MARINE');
		-- ('CIVILIZATION_KONGO' ,'TRAIT_CIVILIZATION_UNIT_GARDE_REPUBLICAINE'),
		-- ('CIVILIZATION_KONGO' ,'TRAIT_CIVILIZATION_UNIT_MEDICINE_MAN');
				
-- IMPROVEMENTS
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES 
('LEADER_HOJO','TRAIT_CIVILIZATION_IMPROVEMENT_GREAT_WALL');
-- ('LEADER_HOJO','TRAIT_CIVILIZATION_IMPROVEMENT_CHATEAU');

-- DISTRICTS
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES 
('LEADER_HOJO','TRAIT_CIVILIZATION_ROYAL_NAVY_DOCKYARD'),
('LEADER_HOJO','TRAIT_CIVILIZATION_STREET_CARNIVAL'),
('LEADER_HOJO','TRAIT_CIVILIZATION_DISTRICT_ACROPOLIS'),
('LEADER_HOJO','TRAIT_CIVILIZATION_DISTRICT_HANSA'),
('LEADER_HOJO','TRAIT_CIVILIZATION_DISTRICT_BATH'),
('LEADER_HOJO','TRAIT_CIVILIZATION_DISTRICT_LAVRA');

-- BUILDINGS
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES 
('LEADER_HOJO','TRAIT_CIVILIZATION_BUILDING_FILM_STUDIO');
-- ('LEADER_HOJO','TRAIT_CIVILIZATION_BUILDING_MADRASA');

-- FROM DLC
INSERT INTO LeaderTraits (LeaderType,TraitType) VALUES 
('LEADER_HOJO','TRAIT_CIVILIZATION_LEGEND_FIVE_SUNS'),
-- ('LEADER_HOJO','TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
('LEADER_HOJO','TRAIT_CIVILIZATION_GOLDEN_LIBERTY'),
('LEADER_HOJO','TRAIT_CIVILIZATION_BUILDING_SUKIENNICE'),
('LEADER_HOJO','TRAIT_CIVILIZATION_IMPROVEMENT_OUTBACK_STATION'),
('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_AZTEC_EAGLE_WARRIOR'),
('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_DIGGER'),
('LEADER_HOJO','TRAIT_CIVILIZATION_UNIT_POLISH_HUSSAR');

--Conflict with HANSA of Germany
-- DELETE FROM LeaderTraits WHERE LeaderType='LEADER_HOJO' AND TraitType='TRAIT_CIVILIZATION_BUILDING_ELECTRONICS_FACTORY';
 
