DELETE FROM CivilizationTraits WHERE CivilizationType='CIVILIZATION_FRANCE' AND TraitType='TRAIT_CIVILIZATION_UNIT_ROMAN_LEGION';

INSERT INTO UnitReplaces (CivUniqueUnitType,ReplacesUnitType) VALUES ('UNIT_JAPANESE_SAMURAI','UNIT_SWORDSMAN'); 
INSERT INTO UnitReplaces (CivUniqueUnitType,ReplacesUnitType) VALUES ('UNIT_POLISH_HUSSAR','UNIT_KNIGHT'); 

UPDATE ModifierArguments SET Value='CIVIC_CIVIL_SERVICE' WHERE ModifierId='TRAIT_NAVAL_CORPS_EARLY' AND Name='CivicType';
UPDATE ModifierArguments SET Value='CIVIC_CIVIL_SERVICE' WHERE ModifierId='TRAIT_NAVAL_ARMIES_EARLY' AND Name='CivicType';

UPDATE UnitCommands SET MaxEra=8 WHERE CommandType='UNITCOMMAND_WONDER_PRODUCTION';




