DELETE FROM CivilizationTraits WHERE CivilizationType='CIVILIZATION_JAPAN';
-- CIVILIZATION TRAITS
-- ABILITIES
INSERT INTO CivilizationTraits
	(CivilizationType,TraitType)
VALUES
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_ADJACENT_DISTRICTS'),
('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME'),
('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_MOTHER_RUSSIA'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_IMPERIAL_FREE_CITIES'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_JAPANESE_SAMURAI'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_AMERICAN_P51'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_FRENCH_GARDE_IMPERIALE'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_GREEK_HOPLITE'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_GERMAN_UBOAT'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_SUMERIAN_WAR_CART'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_ENGLISH_SEADOG'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_SPANISH_CONQUISTADOR'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_RUSSIAN_COSSACK'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_IMPROVEMENT_GREAT_WALL'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_AZTEC_EAGLE_WARRIOR'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_POLISH_HUSSAR'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_IMPROVEMENT_OUTBACK_STATION'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_IMMORTAL'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_IMPROVEMENT_PAIRIDAEZA'),
('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_HYPASPIST');
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_LAST_PROPHET'),
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_TREASURE_FLEET'),
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_PLATOS_REPUBLIC'),
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_ITERU'),
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_WONDER_TOURISM'),
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_NKISI'),
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_FIRST_CIVILIZATION');
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_AMAZON'),
--UNITS
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_UNIT_BRAZILIAN_MINAS_GERAES'),
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_UNIT_ROMAN_LEGION');
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_UNIT_ARABIAN_MAMLUK'),
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_IMPROVEMENT_CHATEAU'),
-- DISTRICTS
-- VALUES
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_ROYAL_NAVY_DOCKYARD'),
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_STREET_CARNIVAL'),
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_DISTRICT_ACROPOLIS'),
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_DISTRICT_HANSA'),
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_DISTRICT_BATH'),
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_DISTRICT_LAVRA'),
-- BUILDINGS
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_BUILDING_FILM_STUDIO'),
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_BUILDING_ELECTRONICS_FACTORY'),
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_BUILDING_STAVE_CHURCH'),
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_BUILDING_TLACHTLI'),
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_MBANZA'),
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_BUILDING_MADRASA'),
--Aztec
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_LEGEND_FIVE_SUNS'),
--Poland
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_GOLDEN_LIBERTY'),
-- ('CIVILIZATION_JAPAN', 'TRAIT_CIVILIZATION_BUILDING_SUKIENNICE'),
--Australia
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_LAND_DOWN_UNDER'),
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_UNIT_DIGGER'),
--Persia
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_SATRAPIES'),
--Macedonia
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_HELLENISTIC_FUSION'),
-- ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_BUILDING_BASILIKOI_PAIDES'),

