-- LEADER TRAITS
-- ALTER TABLE CivilizationTraits ADD LeaderType TEXT;
-- ALTER TABLE LeaderTraits ADD CivilizationType TEXT;
-- UPDATE LeaderTraits SET CivilizationType='CIVILIZATION_AUSTRALIA' WHERE LeaderType='LEADER_PACHACUTI';
-- UPDATE CivilizationTraits SET LeaderType='LEADER_PACHACUTI' WHERE CivilizationType=(SELECT CivilizationType FROM LeaderTraits WHERE LeaderType='LEADER_PACHACUTI');
-- DELETE FROM CivilizationTraits WHERE CivilizationType='CIVILIZATION_AUSTRALIA' AND LeaderType='LEADER_PACHACUTI';
-- DELETE FROM LeaderTraits WHERE LeaderType='LEADER_PACHACUTI';

INSERT INTO LeaderTraits
	(LeaderType,TraitType)
VALUES
('LEADER_PACHACUTI', 'TRAIT_LEADER_UNIT_SULEIMAN_JANISSARY'),
('LEADER_PACHACUTI', 'TRAIT_LEADER_SULEIMAN_GOVERNOR'),
('LEADER_PACHACUTI', 'TRAIT_LEADER_FOUNDER_CARTHAGE');

	-- ('LEADER_PACHACUTI', 'TRAIT_LEADER_DIVINE_WIND'),
	-- ('LEADER_PACHACUTI', 'TRAIT_LEADER_UNIT_ENGLISH_REDCOAT'),
	-- ('LEADER_PACHACUTI', 'TRAIT_LEADER_UNIT_AMERICAN_ROUGH_RIDER'),
	-- ('LEADER_PACHACUTI', 'TRAJANS_COLUMN_TRAIT'),
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_PAX_BRITANNICA'),
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_KILLER_OF_CYRUS'),
	-- ('LEADER_PACHACUTI','FLYING_SQUADRON_TRAIT'),
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_ADVENTURES_ENKIDU'),
	-- ('LEADER_PACHACUTI','CULTURE_KILLS_TRAIT'),
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_MELEE_COASTAL_RAIDS'),
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_EL_ESCORIAL'),
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_MEDITERRANEAN'),
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_ROOSEVELT_COROLLARY'),
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_HOLY_ROMAN_EMPEROR'),
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_MAGNANIMOUS'),
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_GRAND_EMBASSY'),
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH'),
	--FROM DLC
	--Aztec
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_GIFTS_FOR_TLATOANI'),
	--Poland
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_LITHUANIAN_UNION'),
	--Australia
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_CITADEL_CIVILIZATION'),
	--Macedonia
	-- ('LEADER_PACHACUTI','TRAIT_LEADER_TO_WORLDS_END'),
	-- ('LEADER_PACHACUTI', 'TRAIT_LEADER_UNIT_HETAIROI'),
--Persia
-- ('LEADER_PACHACUTI','TRAIT_LEADER_FALL_BABYLON');
-- UNITS
-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_CAMEL_ARCHER'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_GHAZI'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_ARMATOLOS'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_MINUTEMAN'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_LANDSKNECHT'),
	-- ('LEADER_PACHACUTI' , 'TRAIT_CIVILIZATION_UNIT_PANZER'),
	-- ('LEADER_PACHACUTI' , 'TRAIT_CIVILIZATION_UNIT_SASR'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_WOOMERA'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_JAGUAR'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_WARRIOR_PRIEST'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_CHOSEN_INFANTRY'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_UHLAN'),
	-- ('LEADER_PACHACUTI' , 'TRAIT_CIVILIZATION_UNIT_PELTAST'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_PHALANX'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_VULTURE'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_CHOKONU'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_SHIGONG'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_LONGBOWMAN'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_MUGHAL_SOWAR'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_SEPOY'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_HIRDMAN'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_DRUZHINA'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_T34'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_EQUITE'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_ONAGER'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_JINETE'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_TERCIO'),
	-- ('LEADER_PACHACUTI' , 'TRAIT_CIVILIZATION_UNIT_SOHEI'),
	-- ('LEADER_PACHACUTI' , 'TRAIT_CIVILIZATION_UNIT_YAMATO'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_AMAZON'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_AMAZON_SCOUT'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_FATHERLAND_VOLUNTEER'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_BANDEIRANTE'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_HYKSOS_BOWMAN'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_WAR_GALLEY'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_GENDARME'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_FRENCH_MARINE'),
	-- ('LEADER_PACHACUTI' ,'TRAIT_CIVILIZATION_UNIT_GARDE_REPUBLICAINE'),
	-- ('LEADER_PACHACUTI' , 'TRAIT_CIVILIZATION_UNIT_MEDICINE_MAN'),
-- Other Traits
	-- Suzerain
	-- ('LEADER_PACHACUTI','TRAIT_ALL_SUZERAIN_BONUSES'),						
	--Extra Units
	-- ('LEADER_PACHACUTI', 'TRAIT_GDG_CIVILIZATION_EXTRA_UNITS'),
	--Border Growth
	-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_FASTER_BORDER_GROWTH'),
	--Builder Charge
	-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_MANY_BUILDER_CHARGE'),
	-- Settler Production
	-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_FASTEST_SETTLER_PROD'),
	--NEW EXTRA WILD CARD
	-- ('LEADER_PACHACUTI', 'TRAIT_GDG_CIVILIZATION_EXTRA_WILD_CARD'),
	--NEW WONDER PRODUCTION	
	-- ('LEADER_PACHACUTI', 'TRAIT_GDG_CIVILIZATION_WONDER_PRODUCTION'),
	--NEW District PRODUCTION	
	-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_DISTRICT_PRODUCTION'),
	--NEW Building Production
	-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_BUILDING_PRODUCTION'),
	-- Discount Unit Upgrade
	-- ('LEADER_PACHACUTI', 'TRAIT_GDG_CIVILIZATION_UNIT_UPGRADE_DISCOUNT'),
	--City Growth Rate
	-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_CITY_GROWTH'),
	--City Tiles
	-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_CITY_TILES'),
	--City Production
	-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_PRODUCTION'),
	--TRADE
	-- ('LEADER_PACHACUTI', 'TRAIT_GDG_CIVILIZATION_TRADE_YIELDS'),
	--PURCHASE USING FAITH
	-- ('LEADER_PACHACUTI', 'TRAIT_GDG_CIVILIZATION_PURCHASE_UNITS_FAITH'),
	--Minor Open Borders , Influence Points , Religion Spread Distance, Religion Spread Strength
	-- ('LEADER_PACHACUTI', 'TRAIT_GDG_CIVILIZATION_MO_IP_RSD_RSS'),
	--HEAL UNIT AFTER COMBAT	
	-- ('LEADER_PACHACUTI', 'TRAIT_GDG_IRON_SOLDIERS'),
	--Culture Bomb Improvements
	-- ('LEADER_PACHACUTI', 'TRAIT_GDG_CULTURE_BOMB_IMPROVEMENTS');

	--UNIT PRODUCTION
-- 	('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_MELEE_PROD')
-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_RANGED_PROD'),
-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_ANTI_CAVALRY_PROD'),
-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_SIEGE_PROD'),
-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_SUPPORT_PROD'),
-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_HEAVY_CAVALRY_PROD'),
-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_LIGHT_CAVALRY_PROD'),
-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_NAVAL_MELEE_PROD'),
-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_NAVAL_RANGED_PROD'),
-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_NAVAL_RAIDER_PROD'),
-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_AIR_FIGHTER_PROD'),
-- ('LEADER_PACHACUTI','TRAIT_GDG_CIVILIZATION_ONEFORALL_MILITARY_AIR_BOMBER_PROD');




 
