INSERT INTO Types (Type,Kind) VALUES ('TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL','KIND_TRAIT');

INSERT INTO Modifiers (ModifierId,ModifierType) VALUES 
('GDG_TRAIT_CIVILIZATION_ROADS_TO_CAPITAL','MODIFIER_PLAYER_CITIES_GRANT_ROAD_TO_CAPITAL');

INSERT INTO Traits (TraitType,Name,Description) VALUES ('TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL','LOC_TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL_NAME','LOC_TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL_DESCRIPTION');	

INSERT INTO TraitModifiers (TraitType,ModifierId) VALUES 
('TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL','GDG_TRAIT_CIVILIZATION_ROADS_TO_CAPITAL');


INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES 
('CIVILIZATION_AMERICA','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_ARABIA','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_BRAZIL','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_CHINA','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_EGYPT','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_ENGLAND','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_FRANCE','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_GERMANY','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_GREECE','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_INDIA','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_JAPAN','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_KONGO','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_NORWAY','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_RUSSIA','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_SCYTHIA','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_SUMERIA','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_AZTEC','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_POLAND','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_AUSTRALIA','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_PERSIA','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_ROME','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL'),
('CIVILIZATION_MACEDON','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL');

-- PAX BRITANNICA FOR ROME
-- DELETE FROM CivilizationTraits WHERE CivilizationType='CIVILIZATION_ROME' AND TraitType='TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL';
-- INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_ROME','TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL');
-- INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_ROME','TRAIT_LEADER_PAX_BRITANNICA');
















