INSERT INTO Types (Type,Kind)
VALUES ('TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL','KIND_TRAIT');

INSERT INTO Modifiers (ModifierId,ModifierType)
VALUES ('GDG_TRAIT_CIVILIZATION_ROADS_TO_CAPITAL','MODIFIER_PLAYER_CITIES_GRANT_ROAD_TO_CAPITAL');

INSERT INTO Traits (TraitType,Name,Description)
VALUES ('TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL','LOC_TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL_NAME','LOC_TRAIT_GDG_CIVILIZATION_ROADS_TO_CAPITAL_DESCRIPTION');

INSERT INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_LEADER_MAJOR_CIV','GDG_TRAIT_CIVILIZATION_ROADS_TO_CAPITAL');