INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_AMERICA','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_ARABIA','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_BRAZIL','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_CHINA','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_EGYPT','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_ENGLAND','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_FRANCE','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_GERMANY','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_GREECE','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_INDIA','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_JAPAN','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_KONGO','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_NORWAY','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_RUSSIA','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_SCYTHIA','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_SUMERIA','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_ROME','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_AZTEC','TRAIT_CIVILIZATION_ALL_ROADS_TO_ROME');

















