INSERT INTO Improvement_ValidTerrains VALUES 
('IMPROVEMENT_OUTBACK_STATION', 'TERRAIN_TUNDRA',null,null),
('IMPROVEMENT_OUTBACK_STATION', 'TERRAIN_TUNDRA_HILLS',null,null),
('IMPROVEMENT_OUTBACK_STATION', 'TERRAIN_SNOW',null,null),
('IMPROVEMENT_OUTBACK_STATION', 'TERRAIN_SNOW_HILLS',null,null),
('IMPROVEMENT_OUTBACK_STATION', 'TERRAIN_GRASS_HILLS',null,null),
('IMPROVEMENT_OUTBACK_STATION', 'TERRAIN_PLAINS_HILLS',null,null);

INSERT INTO Improvement_ValidFeatures VALUES ('IMPROVEMENT_GREAT_WALL','FEATURE_FLOODPLAINS');
