UPDATE UnitCommands SET MaxEra=8 WHERE CommandType='UNITCOMMAND_WONDER_PRODUCTION';

-- TRAITS FOR THOSE WHO WANT IT TO OTHER CIVS
INSERT INTO Types (Type,Kind) VALUES ('TRAIT_GDG_UNIVERSAL_WONDER_BOOST','KIND_TRAIT');
INSERT INTO Modifiers (ModifierId,ModifierType) VALUES ('TRAIT_GDG_UWB_MId','MODIFIER_PLAYER_ADJUST_UNIT_WONDER_PERCENT');
INSERT INTO ModifierArguments (ModifierId,Name,Value) VALUES ('TRAIT_GDG_UWB_MId','Amount',15);
INSERT INTO Traits (TraitType,Name,Description) VALUES ('TRAIT_GDG_UNIVERSAL_WONDER_BOOST','LOC_TRAIT_GDG_UNIVERSAL_WONDER_BOOST_NAME','LOC_TRAIT_GDG_UNIVERSAL_WONDER_BOOST_DESCRIPTION');	
INSERT INTO TraitModifiers (TraitType,ModifierId) VALUES ('TRAIT_GDG_UNIVERSAL_WONDER_BOOST','TRAIT_GDG_UWB_MId');
-- You can change the value of CIVILIZATION_JAPAN into the given civs below
INSERT INTO CivilizationTraits (CivilizationType,TraitType) VALUES ('CIVILIZATION_MACEDON','TRAIT_GDG_UNIVERSAL_WONDER_BOOST');

-- DONT USE IT IN CHINA BECAUSE IT'S ALREADY GIVEN (CIVILIZATION_CHINA)

-- CIVILIZATION_AMERICA 
-- CIVILIZATION_ARABIA 
-- CIVILIZATION_BRAZIL  
-- CIVILIZATION_EGYPT 
-- CIVILIZATION_ENGLAND 
-- CIVILIZATION_FRANCE 
-- CIVILIZATION_GERMANY 
-- CIVILIZATION_GREECE 
-- CIVILIZATION_INDIA 
-- CIVILIZATION_JAPAN 
-- CIVILIZATION_KONGO 
-- CIVILIZATION_NORWAY 
-- CIVILIZATION_RUSSIA 
-- CIVILIZATION_SCYTHIA 
-- CIVILIZATION_SPAIN 
-- CIVILIZATION_SUMERIA 
-- CIVILIZATION_ROME 
-- CIVILIZATION_AZTEC 
-- CIVILIZATION_AUSTRALIA
-- CIVILIZATION_POLAND
-- CIVILIZATION_MACEDON
-- CIVILIZATION_PERSIA