DELETE FROM CivilizationTraits WHERE CivilizationType='CIVILIZATION_JAPAN' AND TraitType='TRAIT_CIVILIZATION_UNIT_ROMAN_LEGION';
INSERT INTO UnitReplaces (CivUniqueUnitType,ReplacesUnitType) VALUES ('UNIT_JAPANESE_SAMURAI','UNIT_SWORDSMAN'); 
