-- -COLORS CHANGE FOR JAPAN
DELETE FROM Colors WHERE Type='COLOR_PLAYER_JAPAN_PRIMARY';
INSERT INTO Colors (Type,Red,Green,Blue,Alpha) VALUES ('COLOR_PLAYER_JAPAN_PRIMARY',0.701,0,0,1);
DELETE FROM Colors WHERE Type='COLOR_PLAYER_JAPAN_SECONDARY';
INSERT INTO Colors (Type,Red,Green,Blue,Alpha) VALUES ('COLOR_PLAYER_JAPAN_SECONDARY',1,1,1,1);
-- -COLORS CHANGE FOR FRANCE
DELETE FROM Colors WHERE Type='COLOR_PLAYER_FRANCE_PRIMARY';
INSERT INTO Colors (Type,Red,Green,Blue,Alpha) VALUES ('COLOR_PLAYER_FRANCE_PRIMARY',0.0,0.290,0.580,1);
DELETE FROM Colors WHERE Type='COLOR_PLAYER_FRANCE_SECONDARY';
INSERT INTO Colors (Type,Red,Green,Blue,Alpha) VALUES ('COLOR_PLAYER_FRANCE_SECONDARY',0.968,0.882,0.474,1);