-- Types
INSERT INTO Types (Type,Kind) VALUES ('TRAIT_GDG_CIVILIZATION_PRODUCTION','KIND_TRAIT');	
--Modifiers
INSERT INTO Modifiers (ModifierId,ModifierType) VALUES ('TRAIT_CIVILIZATION_GDG_PRODUCTION','MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE');
--Modifier Arguments
INSERT INTO ModifierArguments (ModifierId,Name,Value) VALUES ('TRAIT_CIVILIZATION_GDG_PRODUCTION','Amount',90);
--Traits
INSERT INTO Traits (TraitType,Name,Description) VALUES ('TRAIT_GDG_CIVILIZATION_PRODUCTION','LOCTRAIT_GDG_CIVILIZATION_PRODUCTION_NAME','LOCTRAIT_GDG_CIVILIZATION_PRODUCTION_DESCRIPTION');	
--TraitModifiers
INSERT INTO TraitModifiers (TraitType,ModifierId) VALUES ('TRAIT_GDG_CIVILIZATION_PRODUCTION','TRAIT_CIVILIZATION_GDG_PRODUCTION');

